name: Terraform Workflow

on:
  # Trigger on push to the main branch or a pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Manually trigger destroy
  workflow_dispatch:
    inputs:
      destroy:
        description: "Run terraform destroy before apply"
        required: true
        default: "false"

jobs:
  terraform:
    name: Apply Terraform Configuration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Specify the required Terraform version

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Conditional Terraform Destroy
      if: github.event.inputs.destroy == 'true'   # Only run if manual input triggers destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_username: ${{ secrets.SOLACE_USERNAME }}
        TF_VAR_password: ${{ secrets.SOLACE_PASSWORD }}
        TF_VAR_url: ${{ secrets.SOLACE_URL }}

    - name: Plan Terraform deployment
      run: terraform plan

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve
      env:
        TF_VAR_username: ${{ secrets.SOLACE_USERNAME }}
        TF_VAR_password: ${{ secrets.SOLACE_PASSWORD }}
        TF_VAR_url: ${{ secrets.SOLACE_URL }}
